name: Build Push
description: Build and Push Docker images to a registry
inputs: 
  image:
    description: Name of Docker image to publish
    required: true
  username:
    description: container registry username
    required: true
  password:
    description: container registry password
    required: true
  registry:
    description: Docker container registry to publish built container to.
    required: false
    default: docker.io

runs:
  using: composite
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.image }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.image }}
        cache-to: type=inline