name: Release
on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          npx
          -p semantic-release@19
          -p @semantic-release/changelog@6
          -p @semantic-release/git@10
          semantic-release
